language: python
python:
  - "3.5"
script:
  - python3 -m unittest -v tests/unit_tests/unit_tests
  - pytest
install:
  - pip install -r requirements.txt
notifications:
  email:
    - abramov.ed@phystech.edu
    - evgenabramov239@gmail.com
